### ISSUE TITLE
周本新增虚影宙斯选项

### ISSUE THREAD

**Issue by NEKOice** [MaaXYZ/MCCA#2]
<img width="1031" alt="虚影宙斯" src="https://github.com/MaaXYZ/MCCA/assets/75099085/4d0a94d6-46e0-4a2d-a5db-afb5576f5c28">
开局位置有两个,有概率碰到黄色盾怪额外战斗一次,否则只需要一次boss战斗

**Comment by Tohkahb** [comment]
有好的思路怎么判断开局处于哪一个位置吗

**Comment by Tohkahb** [comment]
已加
