### ISSUE TITLE
新增了一个周本导致无法识别并进行周本自动任务

### ISSUE THREAD

**Issue by W2city** [MaaXYZ/MCCA#20]

**Comment by Tohkahb** [comment]
反馈问题请附上出现问题时的日志文件 debug/maa.log，最好再加上卡住时的截图，谢谢！

**Comment by W2city** [comment]
> 反馈问题请附上出现问题时的日志文件 debug/maa.log，最好再加上卡住时的截图，谢谢！

好的，请看https://gofile.io/d/EZOiYT
[maa.log](https://github.com/user-attachments/files/17192528/maa.log)

**Comment by Tohkahb** [comment]
https://github.com/MaaXYZ/MCCA/commit/5b19538de10a53ddb97685f8fd0e25bf36ff41c0已修

**Comment by Tohkahb** [comment]
已修https://github.com/MaaXYZ/MCCA/commit/5b19538de10a53ddb97685f8fd0e25bf36ff41c0
