### ISSUE TITLE
换抽可以设置吗

### ISSUE THREAD

**Issue by A1130155732** [MaaXYZ/MCCA#24]
请问大佬，换抽逻辑是怎样的啊，有16换2的没点，18换2的点了（好像是访问好友时先出了18换2的，后面再出16换2就不换了？）

![QQ20241003-130043](https://github.com/user-attachments/assets/125c0ef3-08e1-4e0a-b30e-199406429e4a)

这是log：
https://gofile.io/d/mPXDbH

**Comment by Tohkahb** [comment]
本身的逻辑是识别到抽卡券那个图片就会点击，然后点确认，跟几换几没关系

**Comment by Tohkahb** [comment]
本身是按顺序识别的，排在前面的都会先换，换完只后会继续识别剩下的，也就是你这个图理论上会先换第二个，然后再换第六个。但是你发的log里没有定位到截图中换取第六个位置的记录，我也不清楚是哪里的问题

**Comment by Tohkahb** [comment]
另外问一下你分辨率是多大的

**Comment by Tohkahb** [comment]
你是竖屏？

**Comment by A1130155732** [comment]
那就是之前说的，18换2先出现所以换了。后面好友出的16换2没有换。。

**Comment by Tohkahb** [comment]
不会啊，每个人的这个界面都会重新从第一个开始识别，你发的这个情况应该就是属于偶然事件

**Comment by A1130155732** [comment]
好吧，就挺神奇的。。

**Comment by A1130155732** [comment]
打扰大佬了，没注意分辨率
