### ISSUE TITLE
基地换班新增按照技能优先级自动选择角色

### ISSUE THREAD

**Issue by NEKOice** [MaaXYZ/MCCA#3]
按照技能优先级\技能等级选择基地驻员,而不是从前往后选择
或者自选技能来进行排班

**Comment by LBEILC** [comment]
逻辑有些复杂，研究一下看看怎么实现

**Comment by Tohkahb** [comment]
> 逻辑有些复杂，研究一下看看怎么实现

不用管这个吧，现在已经游戏自己已经实装排班预设了
