### ISSUE TITLE
新增军演刷新功能

### ISSUE THREAD

**Issue by NEKOice** [MaaXYZ/MCCA#4]
选择是否刷新
增加几个预设阈值,例如战力小于两万,以挑选官方机器人和下防人进行战斗

**Comment by LBEILC** [comment]
目前来说判断战力的逻辑过于复杂，暂时无法实现，可以等MaaFW2.0出来之后看看能不能实现

**Comment by LBEILC** [comment]
突然想到一个绝妙的点子成功实现了这个功能，预计明天更新一下

**Comment by Tohkahb** [comment]
[Merge pull request](https://github.com/MaaXYZ/MCCA/commit/9936dec72b3ae50966c777c6986b5e2d5e8ec49a) https://github.com/MaaXYZ/MCCA/pull/13 [from LBEILC/dev](https://github.com/MaaXYZ/MCCA/commit/9936dec72b3ae50966c777c6986b5e2d5e8ec49a)
