### ISSUE TITLE
宙斯虚影，在两队进入时会存在问题

### ISSUE THREAD

**Issue by AstralMonster** [MaaXYZ/MCCA#6]
宙斯虚影， 在两队进入时， 二队会因为怪物自动移动，被动的进入战斗， 战斗结束后任务就异常了

**Comment by AstralMonster** [comment]
因为如果你的默认队伍， 存在多队伍配置， 这里建议， 在进入宙斯虚影时， 增加一步， 将二队取消的按钮步骤，这样应该最简单

**Comment by kyokakawaii** [comment]
遇到了相同的问题

**Comment by Tohkahb** [comment]
已修[fix：周本自动关闭第二队](https://github.com/MaaXYZ/MCCA/commit/aecc8199e6b8114f038e7852da938224ef419ee6)
